### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by damien2012eng** [cofe-ai/fast-gector#5]
Received the following error message wehn doing the inference: 
Looks like the `MisMatchedTokenizer` now takes three positional arguments [here](https://github.com/cofe-ai/fast-gector/commit/4da11375ec23458e0da61333616f59ae9a965fcf#diff-f35b28b9f6895b9c921db43067ad54df4790e799e8e495ed306932eac31a3354), only two are given in the predictor class [here](https://github.com/cofe-ai/fast-gector/blob/main/src/predictor.py#L32-L33). 

> Traceback (most recent call last):
  File "/home/ec2-user/gector/fast-gector/predict.py", line 101, in <module>
    main(args)
  File "/home/ec2-user/gector/fast-gector/predict.py", line 49, in main
    pred_batch, cnt = predictor.handle_batch(batch_text)
  File "/home/ec2-user/gector/fast-gector/src/predictor.py", line 76, in handle_batch
    batch_input_dict = self.preprocess(ori_batch)
  File "/home/ec2-user/gector/fast-gector/src/predictor.py", line 114, in preprocess
    input_ids, offsets = self.mismatched_tokenizer.encode(tokens)
  File "/home/ec2-user/gector/fast-gector/utils/mismatched_utils.py", line 22, in encode
    wordpiece_ids = [self.tokenizer_vocab[wordpiece]
  File "/home/ec2-user/gector/fast-gector/utils/mismatched_utils.py", line 22, in <listcomp>
    wordpiece_ids = [self.tokenizer_vocab[wordpiece]
TypeError: 'int' object is not subscriptable

**Comment by Jason3900** [comment]
I'll fix it later. Thanks for your suggestion.

**Comment by Jason3900** [comment]
You can pull the codes and try again now.
