### ISSUE TITLE
Run inference on a GPU EC2 instance

### ISSUE THREAD

**Issue by damien2012eng** [cofe-ai/fast-gector#6]
Hello Jason,

I am using the fine-tuned Roberta model from the GECToR repo to run the inference over a sentences file. I am able to make predictions using the original GECToR. However, I am having issues with the fast-gector. 

This is what I have for the predict.sh: 
> #!/bin/bash
mkdir result
deepspeed --include localhost:0 --master_port 42991 predict.py \
    --batch_size 256 \
    --iteration_count 5 \
    --min_len 3 \
    --max_len 128 \
    --min_error_probability 0.0 \
    --additional_confidence 0.0 \
    --sub_token_mode "average" \
    --max_pieces_per_token 5 \
    --model_dir "/home/ec2-user/fast-gector" \
    --ckpt_id "roberta_1_gectorv2.th" \
    --detect_vocab_path "./data/vocabulary/d_tags.txt" \
    --correct_vocab_path "./data/vocabulary/labels.txt" \
    --pretrained_transformer_path "roberta-base" \
    --input_path "sentences_sample_100.txt" \
    --out_path "result/sentences_sample_100.preds" \
    --special_tokens_fix 1 \
    --detokenize 1 \
    --deepspeed_config "./configs/ds_config_zero1.json"

The error message has been listed below. It looks like the deepspeed is looking for pt files under the model directory, how can I use the fine-tuned model to make predictions in this case? 

> Traceback (most recent call last):
  File "/home/ec2-user/fast-gector/predict.py", line 101, in <module>
    main(args)
  File "/home/ec2-user/fast-gector/predict.py", line 39, in main
    predictor = Predictor(args)
  File "/home/ec2-user/fast-gector/src/predictor.py", line 38, in __init__
    self.model = self.init_model(args)
  File "/home/ec2-user/fast-gector/src/predictor.py", line 59, in init_model
    ds_engine.load_checkpoint(args.model_dir, args.ckpt_id)
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2759, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2793, in _load_checkpoint
    sd_loader = SDLoaderFactory.get_sd_loader(
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 44, in get_sd_loader
    return MegatronSDLoader(ckpt_list, version, checkpoint_engine)
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 216, in __init__
    super().__init__(ckpt_list, version, checkpoint_engine)
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 56, in __init__
    self.check_ckpt_list()
  File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 179, in check_ckpt_list
    assert len(self.ckpt_list) > 0
AssertionError

**Comment by Jason3900** [comment]
you have to convert the huggingface ckpt to deeepspeed format, basically it's not tricky to do so since you only need to make sure the keys in model's state dict is aligned with deepspeed's side.

**Comment by akesh1235** [comment]
> Could you please provide more details? I have not used the deepspeed before. It would also be beneficial to others who switching from GECToR to fast-gector.

I came across the same issue. Could you help me if you have solved this?

**Comment by akesh1235** [comment]
@Jason3900 
Could you please elaborate, I didn't get your point
What do you mean by
Key's in model dict is aligned with with deepseed's side

**Comment by Jason3900** [comment]
I'll try to write a conversion script later. Sorry for the late reply.

**Comment by damien2012eng** [comment]
Thanks for the update, Jason! 
Looking forward to the conversion script.

**Comment by damien2012eng** [comment]
Hi Jason, 

Do you think it would be easier to train the models from the scratch using fast-gector? I saw some [discussions](https://github.com/grammarly/gector/issues?q=is%3Aissue+author%3AJason3900) between you and the people from the Grammarly. 

I will try to follow your discussions and GECToR repo to reproduce the results using fast-gector. Will ask more questions when encountered. Thanks in advance!

**Comment by Jason3900** [comment]
Of course. And btw, maybe you can skip the stage 1 which uses synthetic data to fine-tune the model if your downstream data is of high quality.

**Comment by mrqorib** [comment]
Hi @Jason3900 , did you get a comparable performance by totally skipping stage 1? I also noticed that it seems your code does not have the updates_per_epoch argument that is used in stage 1?

**Comment by AramTaravat** [comment]
> Hello Jason,
> 
> I am using the fine-tuned Roberta model from the GECToR repo to run the inference over a sentences file. I am able to make predictions using the original GECToR. However, I am having issues with the fast-gector.
> 
> This is what I have for the predict.sh:
> 
> > #!/bin/bash
> > mkdir result
> > deepspeed --include localhost:0 --master_port 42991 predict.py 
> >     --batch_size 256 
> >     --iteration_count 5 
> >     --min_len 3 
> >     --max_len 128 
> >     --min_error_probability 0.0 
> >     --additional_confidence 0.0 
> >     --sub_token_mode "average" 
> >     --max_pieces_per_token 5 
> >     --model_dir "/home/ec2-user/fast-gector" 
> >     --ckpt_id "roberta_1_gectorv2.th" 
> >     --detect_vocab_path "./data/vocabulary/d_tags.txt" 
> >     --correct_vocab_path "./data/vocabulary/labels.txt" 
> >     --pretrained_transformer_path "roberta-base" 
> >     --input_path "sentences_sample_100.txt" 
> >     --out_path "result/sentences_sample_100.preds" 
> >     --special_tokens_fix 1 
> >     --detokenize 1 
> >     --deepspeed_config "./configs/ds_config_zero1.json"
> 
> The error message has been listed below. It looks like the deepspeed is looking for pt files under the model directory, how can I use the fine-tuned model to make predictions in this case?
> 
> > Traceback (most recent call last):
> > File "/home/ec2-user/fast-gector/predict.py", line 101, in 
> > main(args)
> > File "/home/ec2-user/fast-gector/predict.py", line 39, in main
> > predictor = Predictor(args)
> > File "/home/ec2-user/fast-gector/src/predictor.py", line 38, in **init**
> > self.model = self.init_model(args)
> > File "/home/ec2-user/fast-gector/src/predictor.py", line 59, in init_model
> > ds_engine.load_checkpoint(args.model_dir, args.ckpt_id)
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2759, in load_checkpoint
> > load_path, client_states = self._load_checkpoint(load_dir,
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2793, in _load_checkpoint
> > sd_loader = SDLoaderFactory.get_sd_loader(
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 44, in get_sd_loader
> > return MegatronSDLoader(ckpt_list, version, checkpoint_engine)
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 216, in **init**
> > super().**init**(ckpt_list, version, checkpoint_engine)
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 56, in **init**
> > self.check_ckpt_list()
> > File "/home/ec2-user/miniconda/envs/gector_env/lib/python3.9/site-packages/deepspeed/runtime/state_dict_factory.py", line 179, in check_ckpt_list
> > assert len(self.ckpt_list) > 0
> > AssertionError

@damien2012eng 
Hi, Did you find out how to correct this error?

**Comment by AramTaravat** [comment]
> I'll try to write a conversion script later. Sorry for the late reply.


@Jason3900 
Hello,
Is there any script yet?
